version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/aws-codebuild-test-0.0.1-SNAPSHOT.war aws-codebuild-test-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - aws-codebuild-test-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
  base-directory: 'target/aws-codebuild-test-0.0.1-SNAPSHOT'
    
    
  